INSERT [dbo].[DEV PORTAL Routing] ([Entity], [Screen Name], [Object], [Type], [Destination], [Use Alternate], [Message Title], [Message Header], [Table Name], [Status Field], [Stored Procedure], [Step], [Sequence], [Verified Date], [Verified Status], [Verified User], [Verified Created], [Approve Label], [Approve Status], [Reject Label], [Reject Status], [Other Label], [Other Status], [ID Field], [Active], [Criteria], [Show History], [Button Message], [GUID], [Attachment Attributes]) VALUES (1000, N'PER_HRA_Local_Distributor_SS', N'HC Document', N'INFO', N'EMPLOYEE', N'Yes', N'HC Document', N'The request has been sent to the manager of HC Document.', N'Per Hra Local Distributor', N'STATUS', N'Local Distributor Communication Email Proc', 10, 20, CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'Yes', N'Audit', CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'APPROVE', N'APPROVED BY MANAGER', N'REJECT', N'REJECTED BY MANAGER', NULL, N'None', N'Distributor', 1, NULL, N'No', NULL, N'baba80e8-c5e8-4c41-87e6-f074d07f02f5', NULL)
GO
INSERT [dbo].[DEV PORTAL Routing] ([Entity], [Screen Name], [Object], [Type], [Destination], [Use Alternate], [Message Title], [Message Header], [Table Name], [Status Field], [Stored Procedure], [Step], [Sequence], [Verified Date], [Verified Status], [Verified User], [Verified Created], [Approve Label], [Approve Status], [Reject Label], [Reject Status], [Other Label], [Other Status], [ID Field], [Active], [Criteria], [Show History], [Button Message], [GUID], [Attachment Attributes]) VALUES (1000, N'PER_HRA_Local_Distributor_SS', N'HC Document', N'APPROVAL', N'MANAGER', N'Yes', N'HC Document', N'The HC Document request has been sent to you.', N'Per Hra Local Distributor', N'STATUS', N'Local Distributor Communication Email Proc', 10, 10, CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'Yes', N'Audit', CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'APPROVE', N'APPROVED BY MANAGER', N'REJECT', N'REJECTED BY MANAGER', NULL, N'None', N'Distributor', 1, NULL, N'No', NULL, N'99c53c84-834e-42a9-8a97-6cad4fe5a05e', NULL)
GO
INSERT [dbo].[DEV PORTAL Routing] ([Entity], [Screen Name], [Object], [Type], [Destination], [Use Alternate], [Message Title], [Message Header], [Table Name], [Status Field], [Stored Procedure], [Step], [Sequence], [Verified Date], [Verified Status], [Verified User], [Verified Created], [Approve Label], [Approve Status], [Reject Label], [Reject Status], [Other Label], [Other Status], [ID Field], [Active], [Criteria], [Show History], [Button Message], [GUID], [Attachment Attributes]) VALUES (3000, N'PER_HRA_Local_Distributor_SS', N'HC Document', N'INFO', N'EMPLOYEE', N'Yes', N'HC Document', N'The request has been sent to the manager of HC Document.', N'Per Hra Local Distributor', N'STATUS', N'Local Distributor Communication Email Proc', 10, 20, CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'Yes', N'Audit', CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'APPROVE', N'APPROVED BY MANAGER', N'REJECT', N'REJECTED BY MANAGER', NULL, N'None', N'Distributor', 1, NULL, N'No', NULL, N'baba80e8-c5e8-4c41-87e6-f074d07f02f5', NULL)
GO
INSERT [dbo].[DEV PORTAL Routing] ([Entity], [Screen Name], [Object], [Type], [Destination], [Use Alternate], [Message Title], [Message Header], [Table Name], [Status Field], [Stored Procedure], [Step], [Sequence], [Verified Date], [Verified Status], [Verified User], [Verified Created], [Approve Label], [Approve Status], [Reject Label], [Reject Status], [Other Label], [Other Status], [ID Field], [Active], [Criteria], [Show History], [Button Message], [GUID], [Attachment Attributes]) VALUES (3000, N'PER_HRA_Local_Distributor_SS', N'HC Document', N'APPROVAL', N'MANAGER', N'Yes', N'HC Document', N'The HC Document request has been sent to you.', N'Per Hra Local Distributor', N'STATUS', N'Local Distributor Communication Email Proc', 10, 10, CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'Yes', N'Audit', CAST(N'2016-03-21 05:25:06.610' AS DateTime), N'APPROVE', N'APPROVED BY MANAGER', N'REJECT', N'REJECTED BY MANAGER', NULL, N'None', N'Distributor', 1, NULL, N'No', NULL, N'99c53c84-834e-42a9-8a97-6cad4fe5a05e', NULL)
GO



INSERT INTO [DEV PORTAL Routing] ([Entity],[Screen Name]                ,[Object]             ,[Type] ,[Destination],[Use Alternate],[Message Title]  ,[Message Header]                                                                                            ,[Table Name]         ,[Status Field],[Stored Procedure]                                                                          ,[Step],[Sequence],[Approve Label],[Approve Status],[Reject Label]        ,[Reject Status],[Other Label]         ,[Other Status],[ID Field],[Active]             ,[Criteria],[Show History],[Button Message],[Attachment Attributes])
VALUES (1000                             ,N'PER_REM_Refund_Request_Emp',N'Emp Refund Request',N'INFO',N'MANAGER'   ,N'Yes'         ,N'Refund Request',N'A Refund Request Application has been received. The relevant data has been attached for your information.',N'PER REM Petty Cash',N'Status'     ,N'[PER_REM_Refund_Request_Emp_Email_Proc] [[Refund_Request_Employee]],[[Refund_Request_VID]],'     ,10        ,10             ,N'APPROVE'      ,N'APPROVED BY MANAGER',N'REJECT'      ,N'REJECTED BY MANAGER',Null          ,N'None'   ,N'Petty Cash Voucher',1         ,Null          ,N'No'           ,Null,Null)
GO

INSERT INTO [DEV PORTAL Routing] ([Entity],[Screen Name]                ,[Object]             ,[Type] ,[Destination],[Use Alternate],[Message Title]  ,[Message Header]                                                                                            ,[Table Name]         ,[Status Field],[Stored Procedure]                                                                          ,[Step],[Sequence],[Approve Label],[Approve Status],[Reject Label]        ,[Reject Status],[Other Label]         ,[Other Status],[ID Field],[Active]             ,[Criteria],[Show History],[Button Message],[Attachment Attributes])
VALUES (1000                             ,N'PER_REM_Refund_Request_Emp',N'Emp Refund Request',N'INFO',N'HR'        ,N'Yes'         ,N'Refund Request',N'A Refund Request Application has been received. The relevant data has been attached for your information.',N'PER REM Petty Cash',N'Status'     ,N'[PER_REM_Refund_Request_Emp_Email_Proc] [[Refund_Request_Employee]],[[Refund_Request_VID]],'     ,10        ,20             ,N'APPROVE'      ,N'APPROVED BY MANAGER',N'REJECT'      ,N'REJECTED BY MANAGER',Null          ,N'None'   ,N'Petty Cash Voucher',1         ,Null          ,N'No'           ,Null,Null)
GO

INSERT INTO [DEV PORTAL Routing] ([Entity],[Screen Name]                ,[Object]             ,[Type] ,[Destination],[Use Alternate],[Message Title]  ,[Message Header]                                                                                            ,[Table Name]         ,[Status Field],[Stored Procedure]                                                                          ,[Step],[Sequence],[Approve Label],[Approve Status],[Reject Label]        ,[Reject Status],[Other Label]         ,[Other Status],[ID Field],[Active]             ,[Criteria],[Show History],[Button Message],[Attachment Attributes])
VALUES (1000                             ,N'PER_REM_Refund_Request_Emp',N'Emp Refund Request',N'INFO',N'EMPLOYEE'  ,N'Yes'         ,N'Refund Request',N'A Refund Request Application has been received. The relevant data has been attached for your information.',N'PER REM Petty Cash',N'Status'     ,N'[PER_REM_Refund_Request_Emp_Email_Proc] [[Refund_Request_Employee]],[[Refund_Request_VID]],'     ,10        ,30             ,N'APPROVE'      ,N'APPROVED BY MANAGER',N'REJECT'      ,N'REJECTED BY MANAGER',Null          ,N'None'   ,N'Petty Cash Voucher',1         ,Null          ,N'No'           ,Null,Null)
GO